import { PlanetSettings } from '@/react-app/pages/Terraformer';

export interface PlanetPreset {
  name: string;
  description: string;
  settings: Omit<PlanetSettings, 'seed'>;
}

export const PLANET_PRESETS: PlanetPreset[] = [
  {
    name: "Earth-like",
    description: "Balanced temperate world with moderate climate",
    settings: {
      landWaterRatio: 0.3,
      coastlineComplexity: 0.6,
      mountainDensity: 0.4,
      climate: 0.4,
      atmosphere: 0.5,
      clouds: 0.7,
      rotationSpeed: 1,
      dayNightCycle: false,
      animationPaused: false,
      backgroundType: 0.25,
      hasRings: false,
      ringDensity: 0.5,
      hasMoon: true,
      moonSize: 0.3,
      audioEnabled: false,
      audioTrack: 0,
      audioVolume: 0.5,
      cameraPreset: 0,
      particleEffects: true,
      planetSize: 1.0,
      autoOrbit: false,
      geologicalTime: 0.2,
      weatherCycle: 0.3,
      climaticShift: 0.1,
      erosionLevel: 0.3,
      timeSpeed: 1,
      temporalPaused: true,
      showTemporalEffects: true,
      tectonicActivity: 0.4,
      oceanLevel: 0,
      atmosphericEvolution: 0.2,
    }
  },
  {
    name: "Ocean World",
    description: "Vast oceans with scattered island chains",
    settings: {
      landWaterRatio: 0.15,
      coastlineComplexity: 0.8,
      mountainDensity: 0.2,
      climate: 0.5,
      atmosphere: 0.6,
      clouds: 0.8,
      rotationSpeed: 1,
      dayNightCycle: false,
      animationPaused: false,
      backgroundType: 0.125,
      hasRings: false,
      ringDensity: 0.5,
      hasMoon: false,
      moonSize: 0.3,
      audioEnabled: false,
      audioTrack: 1,
      audioVolume: 0.5,
      cameraPreset: 0,
      particleEffects: true,
      planetSize: 1.0,
      autoOrbit: false,
      geologicalTime: 0.4,
      weatherCycle: 0.6,
      climaticShift: 0.2,
      erosionLevel: 0.5,
      timeSpeed: 1,
      temporalPaused: true,
      showTemporalEffects: true,
      tectonicActivity: 0.3,
      oceanLevel: 0.1,
      atmosphericEvolution: 0.4,
    }
  },
  {
    name: "Desert Planet",
    description: "Arid world with vast sandy continents",
    settings: {
      landWaterRatio: 0.8,
      coastlineComplexity: 0.3,
      mountainDensity: 0.6,
      climate: 0.8,
      atmosphere: 0.3,
      clouds: 0.2,
      rotationSpeed: 1,
      dayNightCycle: false,
      animationPaused: false,
      backgroundType: 0.75,
      hasRings: true,
      ringDensity: 0.4,
      hasMoon: false,
      moonSize: 0.3,
      audioEnabled: false,
      audioTrack: 2,
      audioVolume: 0.5,
      cameraPreset: 0,
      particleEffects: true,
      planetSize: 1.2,
      autoOrbit: false,
      geologicalTime: 0.7,
      weatherCycle: 0.2,
      climaticShift: 0.6,
      erosionLevel: 0.8,
      timeSpeed: 1,
      temporalPaused: true,
      showTemporalEffects: true,
      tectonicActivity: 0.2,
      oceanLevel: -0.2,
      atmosphericEvolution: 0.1,
    }
  },
  {
    name: "Ice World",
    description: "Frozen planet with icy continents and polar seas",
    settings: {
      landWaterRatio: 0.6,
      coastlineComplexity: 0.4,
      mountainDensity: 0.3,
      climate: 0.1,
      atmosphere: 0.4,
      clouds: 0.5,
      rotationSpeed: 1,
      dayNightCycle: false,
      animationPaused: false,
      backgroundType: 0.0,
      hasRings: false,
      ringDensity: 0.5,
      hasMoon: true,
      moonSize: 0.2,
      audioEnabled: false,
      audioTrack: 0,
      audioVolume: 0.5,
      cameraPreset: 0,
      particleEffects: true,
      planetSize: 0.9,
      autoOrbit: false,
      geologicalTime: 0.9,
      weatherCycle: 0.1,
      climaticShift: 0.1,
      erosionLevel: 0.6,
      timeSpeed: 1,
      temporalPaused: true,
      showTemporalEffects: true,
      tectonicActivity: 0.1,
      oceanLevel: -0.3,
      atmosphericEvolution: 0.3,
    }
  },
  {
    name: "Jungle World",
    description: "Lush verdant planet covered in dense vegetation",
    settings: {
      landWaterRatio: 0.5,
      coastlineComplexity: 0.7,
      mountainDensity: 0.5,
      climate: 0.95,
      atmosphere: 0.7,
      clouds: 0.9,
      rotationSpeed: 1,
      dayNightCycle: false,
      animationPaused: false,
      backgroundType: 0.375,
      hasRings: false,
      ringDensity: 0.5,
      hasMoon: true,
      moonSize: 0.4,
      audioEnabled: false,
      audioTrack: 3,
      audioVolume: 0.5,
      cameraPreset: 0,
      particleEffects: true,
      planetSize: 1.1,
      autoOrbit: false,
      geologicalTime: 0.3,
      weatherCycle: 0.8,
      climaticShift: 0.2,
      erosionLevel: 0.4,
      timeSpeed: 1,
      temporalPaused: true,
      showTemporalEffects: true,
      tectonicActivity: 0.6,
      oceanLevel: 0.1,
      atmosphericEvolution: 0.5,
    }
  },
  {
    name: "Mountainous",
    description: "Rugged world with towering mountain ranges",
    settings: {
      landWaterRatio: 0.7,
      coastlineComplexity: 0.8,
      mountainDensity: 0.9,
      climate: 0.3,
      atmosphere: 0.4,
      clouds: 0.4,
      rotationSpeed: 1,
      dayNightCycle: false,
      animationPaused: false,
      backgroundType: 0.625,
      hasRings: true,
      ringDensity: 0.8,
      hasMoon: true,
      moonSize: 0.25,
      audioEnabled: false,
      audioTrack: 4,
      audioVolume: 0.5,
      cameraPreset: 0,
      particleEffects: true,
      planetSize: 1.3,
      autoOrbit: false,
      geologicalTime: 0.5,
      weatherCycle: 0.3,
      climaticShift: 0.4,
      erosionLevel: 0.2,
      timeSpeed: 1,
      temporalPaused: true,
      showTemporalEffects: true,
      tectonicActivity: 0.9,
      oceanLevel: -0.1,
      atmosphericEvolution: 0.3,
    }
  }
];

export function getRandomPreset(): PlanetPreset {
  return PLANET_PRESETS[Math.floor(Math.random() * PLANET_PRESETS.length)];
}

export function generateRandomSettings(): Omit<PlanetSettings, 'seed'> {
  return {
    landWaterRatio: 0.1 + Math.random() * 0.8,
    coastlineComplexity: 0.2 + Math.random() * 0.6,
    mountainDensity: Math.random() * 0.8,
    climate: Math.random(),
    atmosphere: 0.2 + Math.random() * 0.6,
    clouds: 0.3 + Math.random() * 0.7,
    rotationSpeed: 1,
    dayNightCycle: false,
    animationPaused: false,
    backgroundType: Math.random(),
    hasRings: Math.random() > 0.7,
    ringDensity: 0.3 + Math.random() * 0.7,
    hasMoon: Math.random() > 0.6,
    moonSize: 0.2 + Math.random() * 0.6,
    audioEnabled: false,
    audioTrack: Math.floor(Math.random() * 5),
    audioVolume: 0.3 + Math.random() * 0.4,
    cameraPreset: Math.floor(Math.random() * 8),
    particleEffects: Math.random() > 0.3,
    planetSize: 0.7 + Math.random() * 1.0,
    autoOrbit: Math.random() > 0.8,
    // 4D Temporal Features
    geologicalTime: Math.random() * 0.5,
    weatherCycle: Math.random() * 0.7,
    climaticShift: Math.random() * 0.3,
    erosionLevel: Math.random() * 0.4,
    timeSpeed: 0.5 + Math.random() * 2,
    temporalPaused: Math.random() > 0.6,
    showTemporalEffects: Math.random() > 0.3,
    tectonicActivity: Math.random() * 0.8,
    oceanLevel: (Math.random() - 0.5) * 0.4,
    atmosphericEvolution: Math.random() * 0.5,
  };
}
